### ISSUE TITLE
About contributing

### ISSUE THREAD

**Issue by centsent** [zebresel-com/mongodm#10]
In my opinion, For more developers to contributing code to this repository easily like most open source project, I think you should do something as below:

1. Dockerized. To unified environment of development.
2. Writing test. To make CI easily.
3. Building by CI.
4. Create a CONTRIBUTE.md. To guide those guys who want to contribute to this repository.

BTW, I can submit PRs for step 1-3, let me know your decision by reply, thank you.

**Comment by moehlone** [comment]
Hi @centsent,

first: thanks for caring with this project! Right now I`m on vacation for the next two weeks and I can not do anything within this time. So feel free with the mentioned steps - this will be the most sophisticated solution :-)

See you soon!

**Comment by centsent** [comment]
I am now in working days, I'll submit PR step by step in few days, enjoy your vacation:).

**Comment by moehlone** [comment]
Hi @centsent,

is there any progress on this or can I assume with task one? :-)

Best
Philipp

**Comment by centsent** [comment]
Sorry to be so late, I am working on task one but was stunned on dealing with docker mongodb authentication, I will solve this problem and submit the PR before Oct 28th.

**Comment by centsent** [comment]
FYR, Here is my `Dockerfile` and `docker-compose.yml`:

## Dockerfile
```
FROM golang

ENV APP_DIR $GOPATH/src/mongodm

RUN mkdir -p $APP_DIR && \
    # use godep to manage dependencies
    go get -u github.com/golang/dep/cmd/dep

ADD . $APP_DIR

WORKDIR $APP_DIR
```

## docker-compose.yml

```yaml
version: '3'
services:
  test:
    depends_on:
      - mongodb
    links:
      - mongodb
    build:
      context: .
    image: mongodm
    volumes:
      - ".:/go/src/mongodm"
    command: bash -c "dep ensure && go test"
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    command: mongod --auth
```
